openapi: 3.0.0
info:
  title: Client Contact API
  version: 1.0.0
  description: API для управления клиентами и их контактной информацией.

servers:
  - url: http://localhost:8080
    description: Локальный сервер для разработки

paths:
  /api/clients:
    get:
      summary: Получение списка всех клиентов
      responses:
        '200':
          description: Успешное получение списка клиентов
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: "John Doe"
    post:
      summary: Добавление нового клиента
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "Jane Smith"
      responses:
        '201':
          description: Клиент успешно создан
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 2
                  name:
                    type: string
                    example: "Jane Smith"

  /api/clients/{id}:
    get:
      summary: Получение информации о клиенте по ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID клиента
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Успешное получение информации о клиенте
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  name:
                    type: string
                    example: "John Doe"
        '404':
          description: Клиент не найден

  /api/clients/{id}/contacts:
    post:
      summary: Добавление нового контакта для клиента
      parameters:
        - name: id
          in: path
          required: true
          description: ID клиента
          schema:
            type: integer
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                contactType:
                  type: string
                  example: "PHONE"
                contactValue:
                  type: string
                  example: "+7(123)456-78-90"
      responses:
        '201':
          description: Контакт успешно добавлен
          content:
            application/json:
              schema:
                type: object
                properties:
                  contactType:
                    type: string
                    example: "PHONE"
                  contactValue:
                    type: string
                    example: "+7(123)456-78-90"
        '404':
          description: Клиент не найден
    get:
      summary: Получение списка всех контактов клиента по ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID клиента
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Успешное получение списка контактов клиента
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    contactType:
                      type: string
                      example: "PHONE"
                    contactValue:
                      type: string
                      example: "+7(123)456-78-90"
        '404':
          description: Клиент не найден

  /api/clients/{id}/contacts/type:
    get:
      summary: Получение списка контактов определенного типа для клиента по ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID клиента
          schema:
            type: integer
            example: 1
        - in: query
          name: contactType
          required: true
          description: Тип контакта
          schema:
            type: string
            enum:
              - PHONE
              - EMAIL
      responses:
        '200':
          description: Успешное получение списка контактов указанного типа
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    contactType:
                      type: string
                      example: "PHONE"
                    contactValue:
                      type: string
                      example: "+7(123)456-78-90"
components:
  schemas:
    Client:
      type: object
      properties:
        id:
          type: integer
          format: int32
          description: 'id клиента'
        name:
          type: string
          description: 'имя клиента'
        contacts:
          type: array
          items:
            $ref: '#/components/schemas/Contact'
    Contact:
      type: object
      properties:
        id:
          type: integer
          format: int32
          description: 'id контакта'
        contactType:
          type: string
          description: 'тип контакта'
          enum:
            - PHONE
            - EMAIL
        contactValue:
          type: string
          description: 'значение контакта'
        client_id:
          type: integer
          description: 'id клиента'